# Site settings
title: 어린콩의 개발일지
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jybin96.github.io/" # the base hostname & protocol for your site
# User settings
username: 어린콩
user_description: 아직은 많이 부족하지만 개발공부를하면서 점차 성장하는 개발자가 되겠습니다!
user_title: Software Engineer
email: jybin96@changwon.ac.kr
featured_img: /assets/youngbean.jpg
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
